[package]
name = "rstore"
version = "0.1.0"
authors = ["Paul Soucy <paul@dev-smart.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hash-roll = "0.2.0"